import { HERMES_PROVIDER_API_KEY_ENV, HERMES_PROVIDER_BASE_URL_ENV } from "./env.js";

/**
 * The generated Hermes `model-provider` plugin bytes: the provider's own
 * file and its manifest, rendered from the routing's base URL, the pinned
 * model, and the levels the live catalog publishes. This module renders
 * bytes only — it holds no config or env routing, and never imports
 * routing.ts (routing imports these bytes and re-exports the shared
 * identity constants here, so no caller changes).
 */
export const HERMES_PROVIDER_ID = "aiand";
/** Stamp both generated plugin files carry, so off never unlinks a hand edit. */
export const HERMES_PLUGIN_STAMP = "generated by aiand";

/**
 * Every catalog model's published reasoning levels, keyed by model id, for
 * the generated Hermes plugin. Models publishing none (`null` or an empty
 * list) are dropped: an undeclared model must keep Hermes's own default
 * rather than have a level invented for it.
 */
export function hermesReasoningLevels(
  catalog: readonly { id: string; reasoning_efforts: string[] | null }[],
): ReadonlyMap<string, readonly string[]> {
  const levels = new Map<string, readonly string[]>();
  for (const model of catalog) {
    if (model.reasoning_efforts && model.reasoning_efforts.length > 0) {
      levels.set(model.id, model.reasoning_efforts);
    }
  }
  return levels;
}

/**
 * The routing's own model provider, shared by overlay and persistent `on`:
 * Hermes has no built-in ai& entry, so routing ships one as a
 * `model-provider` plugin. The profile drops the tool-role `name` before
 * sending (gateways that reject unnamed tool roles would fail the session
 * otherwise), reads its key and base URL from the dedicated `.env` names,
 * lists the pinned model as its fallback, and carries each model's
 * published reasoning levels so Hermes clamps a user's pick onto a set the
 * gateway accepts instead of letting the engine default decide.
 */
export function buildHermesProviderFiles({
  baseUrl,
  model,
  reasoningLevels,
}: {
  baseUrl: string;
  model: string | undefined;
  reasoningLevels: ReadonlyMap<string, readonly string[]>;
}): { initPy: string; pluginYaml: string } {
  // Sorted keys keep the rendered literal byte-stable for the same catalog.
  const reasoningLiteral = JSON.stringify(
    Object.fromEntries([...reasoningLevels].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))),
  );
  const modelIds = model === undefined ? [] : [model];
  const modelValues = modelIds.map((id) => JSON.stringify(id)).join(", ");
  // A 1-tuple needs a trailing comma in Python.
  const pythonTuple = modelIds.length === 1 ? `${modelValues},` : modelValues;
  const initPy = `"""ai& provider ${HERMES_PLUGIN_STAMP}."""

from agent.reasoning_effort import clamp_effort
from providers import register_provider
from providers.base import ProviderProfile

# Each model's published reasoning levels (from the live ai& catalog):
AIAND_REASONING_LEVELS = ${reasoningLiteral}


class AiandProfile(ProviderProfile):
    def prepare_messages(self, messages):
        prepared = []
        for message in messages:
            item = dict(message)
            if item.get("role") == "tool":
                item.pop("name", None)
            prepared.append(item)
        return prepared

    def supported_reasoning_efforts(self, model):
        return AIAND_REASONING_LEVELS.get(model)

    def default_reasoning_config(self, model=None):
        levels = AIAND_REASONING_LEVELS.get(model or "")
        if not levels:
            return None
        return {"enabled": True, "effort": levels[0]}

    def build_api_kwargs_extras(self, reasoning_config=None, **context):
        model = context.get("model")
        levels = AIAND_REASONING_LEVELS.get(model or "")
        if levels:
            effort = (str((reasoning_config or {}).get("effort") or "")).strip().lower()
            enabled = (reasoning_config or {}).get("enabled", True) is not False
            if enabled and effort:
                return {}, {"reasoning_effort": clamp_effort(effort, tuple(levels))}
            if not enabled:
                return {}, {"reasoning_effort": "none"}
        return {}, {}


aiand = AiandProfile(
    name=${JSON.stringify(HERMES_PROVIDER_ID)},
    display_name="aiand",
    description="ai& gateway through aiand",
    api_mode="chat_completions",
    env_vars=(${JSON.stringify(HERMES_PROVIDER_API_KEY_ENV)}, ${JSON.stringify(HERMES_PROVIDER_BASE_URL_ENV)}),
    base_url=${JSON.stringify(baseUrl)},
    fallback_models=(${pythonTuple}),
    supports_vision=True,
)

register_provider(aiand)
`;
  const pluginYaml = `name: ${HERMES_PROVIDER_ID}
kind: model-provider
version: 1.0.0
description: ai& gateway through aiand, ${HERMES_PLUGIN_STAMP}
`;
  return { initPy, pluginYaml };
}
