/**
 * Shared Hermes routing content: the pure builder enable() and the overlay
 * both write, so persistent wiring and throwaway sessions cannot drift.
 * No filesystem or snapshot access here — this module renders bytes from
 * bytes (provider plugin, providers.aiand block, top-level model pin, and
 * the routing .env), and reads them back the same way probe() and off do.
 */
/** The provider id, and the overlay .env names that feed it. */
export const HERMES_PROVIDER_ID = "aiand";
export const HERMES_PROVIDER_API_KEY_ENV = "AIAND_HERMES_API_KEY";
/**
 * The overlay/persistent `.env` name for the gateway base URL, read back
 * only by the generated provider plugin (`env_vars` in
 * buildHermesProviderFiles): the `.env` defines it, the plugin declares it,
 * Hermes injects it at runtime. Deliberately module-private — no other
 * module names it; the plugin and the `.env` meet through the built bytes.
 */
const HERMES_PROVIDER_BASE_URL_ENV = "AIAND_HERMES_BASE_URL";
/**
 * Ownership marker aiand stamps on its `providers.aiand` block so off can
 * tell its block from the user's. Hermes ignores unknown provider keys (one
 * log warning per process), so the stamp survives the config rewrites that
 * would drop a comment; the AddedState record backstops it when even the
 * stamp is gone.
 */
const HERMES_MARKER_KEY = "managed_by";
const HERMES_MARKER_VALUE = "aiand";
/** Stamp both generated plugin files carry, so off never unlinks a hand edit. */
export const HERMES_PLUGIN_STAMP = "generated by aiand";

/** Recovery hint for a Hermes home that holds a block aiand must not touch. */
export const FOREIGN_BLOCK_HINT =
  "Remove or rename the foreign block by hand, then run aiand hermes on again.";

/**
 * dotenv lines the routing owns or shadows: our own dedicated pair (a stale
 * pair from a hand-copied overlay must never win over fresh routing) and the
 * user's ANTHROPIC_* entries (Hermes prefers its saved .env over process
 * env, so they must never shadow the aiand routing, whichever end of the
 * file their dotenv loader prefers).
 */
const SHADOWED_ENV_RE =
  /^[ \t]*(?:export[ \t]+)?(?:ANTHROPIC_(?:API_KEY|BASE_URL|TOKEN)|AIAND_HERMES_(?:API_KEY|BASE_URL))[ \t]*=/;
/** Only our own dedicated pair: what off strips (user lines stay). */
export const OWNED_ENV_RE = /^[ \t]*(?:export[ \t]+)?AIAND_HERMES_(?:API_KEY|BASE_URL)[ \t]*=/;

function envValuePattern(name: string): RegExp {
  return new RegExp(`^([ \\t]*(?:export[ \\t]+)?${name}[ \\t]*=[ \\t]*).*$`);
}
/**
 * The one content builder for Hermes routing, used by both enable() and
 * sessionLaunch() so persistent wiring and the throwaway overlay cannot
 * drift. `envText`/`configText` are the existing file bytes ("" when the
 * file is missing); `model` is the pinned model, or undefined for native
 * (the provider block stays model-free). The top-level `model:` pin stays
 * with the caller — the overlay pins unconditionally through
 * pinHermesModel, while enable() applies its keep/set-aside policy there —
 * so this builder covers the provider block, the `.env`, and the plugin.
 */
export function buildHermesWrites({
  apiKey,
  baseUrl,
  model,
  envText,
  configText,
}: {
  apiKey: string;
  baseUrl: string;
  model: string | undefined;
  envText: string;
  configText: string;
}): {
  env: string;
  config: string;
  initPy: string;
  pluginYaml: string;
  droppedEnvLines: string[];
} {
  const rendered = renderHermesEnv(envText, { apiKey, baseUrl });
  return {
    env: rendered.text,
    droppedEnvLines: rendered.droppedUserLines,
    config: pinHermesProvider(configText, baseUrl, model),
    ...buildHermesProviderFiles({ baseUrl, model }),
  };
}
/**
 * Render the routing `.env`: every other line survives byte-identical
 * (comments, blanks, unrelated keys), shadowed lines are dropped, and our
 * dedicated pair is appended. JSON.stringify quotes each value so a key
 * with spaces or # stays one dotenv entry.
 */
function renderHermesEnv(
  existingText: string,
  { apiKey, baseUrl }: { apiKey: string; baseUrl: string },
): { text: string; droppedUserLines: string[] } {
  const kept: string[] = [];
  const droppedUserLines: string[] = [];
  for (const line of existingText.split("\n")) {
    if (!SHADOWED_ENV_RE.test(line)) {
      kept.push(line);
      continue;
    }
    // Stale pairs of ours go quietly; the user's own ANTHROPIC_* lines are
    // reported, so enable() can warn and off can hand them back.
    if (!OWNED_ENV_RE.test(line)) droppedUserLines.push(line);
  }
  const joined = kept.join("\n");
  const prefix = joined === "" ? "" : joined.endsWith("\n") ? joined : `${joined}\n`;
  return {
    text:
      `${prefix}${HERMES_PROVIDER_API_KEY_ENV}=${JSON.stringify(apiKey)}\n` +
      `${HERMES_PROVIDER_BASE_URL_ENV}=${JSON.stringify(baseUrl)}\n`,
    droppedUserLines,
  };
}

/** The value of one dotenv variable, unquoted, or undefined when absent/empty. */
export function readEnvValue(text: string, name: string): string | undefined {
  // Horizontal whitespace only: `\s` would eat the newline and capture the
  // next line's value for an empty assignment.
  const match = new RegExp(
    `^[ \\t]*(?:export[ \\t]+)?${name}[ \\t]*=[ \\t]*(.*?)[ \\t]*$`,
    "m",
  ).exec(text);
  if (!match) return undefined;
  const value = unquoteYaml(match[1] ?? "");
  return value === "" ? undefined : value;
}

/** Swap one dotenv variable's value in place; every other byte survives. */
export function replaceEnvValue(text: string, name: string, value: string): string {
  const pattern = envValuePattern(name);
  // A replacer function, not a `$1...` template: a key carrying `$&` must
  // land literally, not as the matched line spliced back into itself.
  return text
    .split("\n")
    .map((line) =>
      pattern.test(line)
        ? line.replace(pattern, (_match, prefix) => `${prefix}${JSON.stringify(value)}`)
        : line,
    )
    .join("\n");
}

/** A YAML scalar without its quotes: ours are JSON-stringified, the user's may be bare. */
function unquoteYaml(value: string): string {
  const text = value.trim();
  if (text.length >= 2 && text.startsWith('"') && text.endsWith('"')) {
    try {
      return JSON.parse(text) as string;
    } catch {
      return text.slice(1, -1);
    }
  }
  if (text.length >= 2 && text.startsWith("'") && text.endsWith("'")) {
    return text.slice(1, -1).replace(/''/g, "'");
  }
  return text;
}

/** A comment line never ends a section: it floats wherever YAML allows. */
function isCommentLine(line: string): boolean {
  return line.trimStart().startsWith("#");
}

/** Whether a line belongs to the section body: indented, blank, or a comment. */
function isSectionBodyLine(line: string): boolean {
  return line.trim() === "" || /^\s/.test(line) || isCommentLine(line);
}

/** A top-level `name:` section's body: scalar sections (fresh `model: ""`) carry none. */
function sectionRange(lines: string[], name: string): { at: number; end: number } | null {
  const at = lines.findIndex((line) => new RegExp(`^${name}\\s*:`).test(line));
  if (at === -1) return null;
  const scalar = new RegExp(`^${name}\\s*:\\s*\\S`).test(lines[at]!);
  let end = at + 1;
  if (!scalar) {
    while (end < lines.length && isSectionBodyLine(lines[end]!)) end += 1;
    while (end > at + 1 && lines[end - 1]!.trim() === "") end -= 1;
  }
  return { at, end };
}

/** The `providers:` body plus our block's span inside it, anchored to the section indent. */
function aiandBlockSpan(
  lines: string[],
): { at: number; end: number; indent: string; subAt: number; subEnd: number } | null {
  const section = sectionRange(lines, "providers");
  if (!section) return null;
  const body = lines.slice(section.at + 1, section.end);
  const indent = /^(\s+)\S/.exec(body.find((line) => /^\s+\S/.test(line)) ?? "")?.[1] ?? "  ";
  // Anchored to the section indent, so a deeper `aiand:` nested inside
  // another provider's own config can never match.
  const subAt = body.findIndex((line) => new RegExp(`^${indent}aiand\\s*:`).test(line));
  if (subAt === -1) return null;
  // The block's body runs while lines stay more indented than its own key.
  let subEnd = subAt + 1;
  while (
    subEnd < body.length &&
    (body[subEnd]!.trim() === "" ||
      body[subEnd]!.startsWith(`${indent} `) ||
      isCommentLine(body[subEnd]!))
  )
    subEnd += 1;
  return { at: section.at, end: section.end, indent, subAt, subEnd };
}

/** One field of our `providers.aiand` block, unquoted, or undefined when absent. */
export function readProviderField(text: string, field: string): string | undefined {
  const lines = text.split("\n");
  const span = aiandBlockSpan(lines);
  if (!span) return undefined;
  const body = lines.slice(span.at + 1, span.end);
  const match = body
    .slice(span.subAt + 1, span.subEnd)
    .map((line) => new RegExp(`^${span.indent}  ${field}\\s*:\\s*(.+?)\\s*$`).exec(line))
    .find((found) => found !== null);
  return match ? unquoteYaml(match[1] ?? "") : undefined;
}

/** True when our ownership stamp sits on the `providers.aiand` block. */
export function hasHermesMarker(text: string): boolean {
  return readProviderField(text, HERMES_MARKER_KEY) === HERMES_MARKER_VALUE;
}

/** True when a `providers.aiand` block exists, marked or foreign. */
export function hasProviderAiand(text: string): boolean {
  return aiandBlockSpan(text.split("\n")) !== null;
}

/** The `model:` section's scalar value (a fresh `model: ""` sentinel), if it is one. */
function modelScalar(text: string): string | undefined {
  const lines = text.split("\n");
  const at = lines.findIndex((line) => /^model\s*:/.test(line));
  if (at === -1 || !/^model\s*:\s*\S/.test(lines[at]!)) return undefined;
  return unquoteYaml(lines[at]!.replace(/^model\s*:\s*/, ""));
}

/** One field of the top-level `model:` mapping; `default` also reads a scalar section. */
export function readModelField(text: string, field: "provider" | "default"): string | undefined {
  if (field === "default") {
    const scalar = modelScalar(text);
    if (scalar !== undefined) return scalar === "" ? undefined : scalar;
  }
  const lines = text.split("\n");
  const section = sectionRange(lines, "model");
  if (!section) return undefined;
  const body = lines.slice(section.at + 1, section.end);
  const indent = /^(\s+)\S/.exec(body.find((line) => /^\s+\w/.test(line)) ?? "")?.[1] ?? "  ";
  // `model` is Hermes's alias for the model id — an alias or `default` line is ours to read.
  const pattern =
    field === "provider"
      ? new RegExp(`^${indent}provider\\s*:\\s*(.+?)\\s*$`)
      : new RegExp(`^${indent}(?:"?default"?|model)\\s*:\\s*(.+?)\\s*$`);
  const match = body.map((line) => pattern.exec(line)).find((found) => found != null);
  return match ? unquoteYaml(match[1] ?? "") : undefined;
}

/** The raw source line of one `model:` field, so off can hand back the exact bytes. */
export function modelFieldLine(text: string, field: "provider" | "default"): string | undefined {
  const lines = text.split("\n");
  const section = sectionRange(lines, "model");
  if (!section) return undefined;
  const body = lines.slice(section.at + 1, section.end);
  const indent = /^(\s+)\S/.exec(body.find((line) => /^\s+\w/.test(line)) ?? "")?.[1] ?? "  ";
  const pattern =
    field === "provider"
      ? new RegExp(`^${indent}provider\\s*:`)
      : new RegExp(`^${indent}(?:"?default"?|model)\\s*:`);
  return body.find((line) => pattern.test(line));
}
/**
 * The routing's own model provider, shared by overlay and persistent `on`:
 * Hermes has no built-in ai& entry, so routing ships one as a
 * `model-provider` plugin. The profile drops the tool-role `name` before
 * sending (gateways that reject unnamed tool roles would fail the session
 * otherwise), reads its key and base URL from the dedicated `.env` names,
 * and lists the pinned model as its fallback.
 */
function buildHermesProviderFiles({
  baseUrl,
  model,
}: {
  baseUrl: string;
  model: string | undefined;
}): { initPy: string; pluginYaml: string } {
  const modelIds = model === undefined ? [] : [model];
  const modelValues = modelIds.map((id) => JSON.stringify(id)).join(", ");
  // A 1-tuple needs a trailing comma in Python.
  const pythonTuple = modelIds.length === 1 ? `${modelValues},` : modelValues;
  const initPy = `"""ai& provider ${HERMES_PLUGIN_STAMP}."""

from providers import register_provider
from providers.base import ProviderProfile


class AiandProfile(ProviderProfile):
    def prepare_messages(self, messages):
        prepared = []
        for message in messages:
            item = dict(message)
            if item.get("role") == "tool":
                item.pop("name", None)
            prepared.append(item)


aiand = AiandProfile(
    name=${JSON.stringify(HERMES_PROVIDER_ID)},
    display_name="aiand",
    description="ai& gateway through aiand",
    api_mode="chat_completions",
    env_vars=(${JSON.stringify(HERMES_PROVIDER_API_KEY_ENV)}, ${JSON.stringify(HERMES_PROVIDER_BASE_URL_ENV)}),
    base_url=${JSON.stringify(baseUrl)},
    fallback_models=(${pythonTuple}),
    supports_vision=True,
)

register_provider(aiand)
`;
  const pluginYaml = `name: ${HERMES_PROVIDER_ID}
kind: model-provider
version: 1.0.0
description: ai& gateway through aiand, ${HERMES_PLUGIN_STAMP}
`;
  return { initPy, pluginYaml };
}
/**
 * Upsert the `providers.aiand` block of a hermes config: the connection
 * fields always, the model list only when a model is pinned (`native`
 * leaves the provider model-free, so Hermes's own default decides).
 * Hermes seeds no `providers:` key of its own, but a user one is rewritten
 * where it stands; other providers and unrelated keys stay put. `native`
 * is the only case with an empty model list — a pinned launch always names
 * exactly the routed model. The ownership stamp rides last: Hermes ignores
 * the unknown key, and off uses it to tell its block from the user's.
 */
export function pinHermesProvider(
  text: string,
  baseUrl: string,
  model: string | undefined,
): string {
  const entry = (indent: string) => [
    `${indent}aiand:`,
    `${indent}  name: aiand`,
    `${indent}  base_url: ${JSON.stringify(baseUrl)}`,
    `${indent}  key_env: ${HERMES_PROVIDER_API_KEY_ENV}`,
    `${indent}  transport: chat_completions`,
    ...(model === undefined
      ? []
      : [
          `${indent}  default_model: ${JSON.stringify(model)}`,
          `${indent}  models: ${JSON.stringify([model])}`,
        ]),
    `${indent}  discover_models: false`,
    `${indent}  ${HERMES_MARKER_KEY}: ${JSON.stringify(HERMES_MARKER_VALUE)}`,
  ];
  const lines = text.split("\n");
  const at = lines.findIndex((line) => /^providers\s*:/.test(line));
  if (at === -1) {
    const gap = lines.length > 0 && lines[lines.length - 1]!.trim() !== "" ? [""] : [];
    return [...lines, ...gap, "providers:", ...entry("  ")].join("\n");
  }
  // The scalar form carries no body; a mapping's runs to the next column-0
  // line, blank lines and comments included (then minus the trailing blanks).
  const scalar = /^providers\s*:\s*\S/.test(lines[at]!);
  let end = at + 1;
  if (!scalar) {
    while (end < lines.length && isSectionBodyLine(lines[end]!)) end += 1;
    while (end > at + 1 && lines[end - 1]!.trim() === "") end -= 1;
  }
  const body = scalar ? [] : lines.slice(at + 1, end);
  const indent = /^(\s+)\S/.exec(body.find((line) => /^\s+\S/.test(line)) ?? "")?.[1] ?? "  ";
  // Anchored to the section indent, so a deeper `aiand:` nested inside
  // another provider's own config can never match.
  const providerKey = new RegExp(`^${indent}aiand\\s*:`);
  const subAt = body.findIndex((line) => providerKey.test(line));
  if (subAt === -1)
    return [
      ...lines.slice(0, at),
      "providers:",
      ...body,
      ...entry(indent),
      ...lines.slice(end),
    ].join("\n");
  // The block's body runs while lines stay more indented than its own key.
  let subEnd = subAt + 1;
  while (
    subEnd < body.length &&
    (body[subEnd]!.trim() === "" ||
      body[subEnd]!.startsWith(`${indent} `) ||
      isCommentLine(body[subEnd]!))
  )
    subEnd += 1;
  return [
    ...lines.slice(0, at),
    "providers:",
    ...body.slice(0, subAt),
    ...entry(indent),
    ...body.slice(subEnd),
    ...lines.slice(end),
  ].join("\n");
}
/**
 * Remove our `providers.aiand` block again, dropping the `providers:` map
 * with it when nothing else is left. The exact inverse of
 * pinHermesProvider for a file enable() wrote and nobody touched since.
 */
export function stripHermesProvider(text: string): string {
  const lines = text.split("\n");
  const span = aiandBlockSpan(lines);
  if (!span) return text;
  const body = [
    ...lines.slice(span.at + 1, span.at + 1 + span.subAt),
    ...lines.slice(span.at + 1 + span.subEnd, span.end),
  ];
  if (body.every((line) => line.trim() === "")) {
    return [...lines.slice(0, span.at), ...lines.slice(span.end)].join("\n");
  }
  return [...lines.slice(0, span.at), "providers:", ...body, ...lines.slice(span.end)].join("\n");
}
/**
 * Rewrite (or add) the top-level `model:` mapping of a hermes config:
 * `provider: aiand` always, the pinned model as `default` only when one
 * is given. Indentation follows the section's own keys; the body-less scalar
 * form (`model: ""`, a fresh install's sentinel) is replaced by the mapping.
 * Hermes accepts `model` as an alias for the model id — an alias or
 * `default` line is rewritten to `default`, the key we own.
 */
export function pinHermesModel(text: string, model: string | undefined): string {
  const lines = text.split("\n");
  const pinned = model === undefined ? null : `default: ${JSON.stringify(model)}`;
  const at = lines.findIndex((line) => /^model\s*:/.test(line));
  if (at === -1) {
    const block = ["model:", "  provider: aiand", ...(pinned ? [`  ${pinned}`] : [])];
    return [...block, ...lines].join("\n");
  }
  // The scalar form carries no body; a mapping's runs to the next column-0
  // line, blank lines and comments included (then minus the trailing blanks).
  const scalar = /^model\s*:\s*\S/.test(lines[at]!);
  let end = at + 1;
  if (!scalar) {
    while (end < lines.length && isSectionBodyLine(lines[end]!)) end += 1;
    while (end > at + 1 && lines[end - 1]!.trim() === "") end -= 1;
  }
  const body = scalar ? [] : lines.slice(at + 1, end);
  const indent = /^(\s+)\S/.exec(body.find((line) => /^\s+\w/.test(line)) ?? "")?.[1] ?? "  ";
  const providerKey = new RegExp(`^${indent}provider\\s*:`);
  const modelKey = new RegExp(`^${indent}(?:"?default"?|model)\\s*:`);
  const out: string[] = [];
  let providerAt = -1;
  for (const line of body) {
    if (providerKey.test(line)) {
      out.push(`${indent}provider: aiand`);
      providerAt = out.length - 1;
    } else if (!(pinned !== null && modelKey.test(line))) {
      out.push(line); // dropped: rewritten after the provider line
    }
  }
  if (providerAt === -1) {
    out.unshift(`${indent}provider: aiand`);
    providerAt = 0;
  }
  if (pinned !== null) out.splice(providerAt + 1, 0, `${indent}${pinned}`);
  // The header becomes the bare `model:` key: a scalar value left standing
  // in front of the mapping would not parse.
  return [...lines.slice(0, at), "model:", ...out, ...lines.slice(end)].join("\n");
}
/**
 * Route one `model:` field through aiand without touching the other, for
 * the keeps the overlay never performs: a kept servable default stays
 * byte-identical while its provider flips. Values already routing stay put.
 */
export function setHermesModelProvider(text: string): string {
  const lines = text.split("\n");
  const section = sectionRange(lines, "model");
  if (!section) return text;
  const body = lines.slice(section.at + 1, section.end);
  const indent = /^(\s+)\S/.exec(body.find((line) => /^\s+\w/.test(line)) ?? "")?.[1] ?? "  ";
  const providerKey = new RegExp(`^${indent}provider\\s*:`);
  const at = body.findIndex((line) => providerKey.test(line));
  if (at !== -1) {
    if (unquoteYaml(body[at]!.replace(providerKey, "")) === HERMES_PROVIDER_ID) return text;
    body[at] = `${indent}provider: ${HERMES_PROVIDER_ID}`;
  } else {
    body.unshift(`${indent}provider: ${HERMES_PROVIDER_ID}`);
  }
  // The header becomes the bare `model:` key: a scalar sentinel left
  // standing in front of the mapping would not parse.
  return [...lines.slice(0, section.at), "model:", ...body, ...lines.slice(section.end)].join("\n");
}
/** Put one recorded `model:` line back (or delete the field when none was recorded). */
export function restoreHermesModelLine(
  text: string,
  field: "provider" | "default",
  recorded: string | undefined,
): string {
  const lines = text.split("\n");
  const section = sectionRange(lines, "model");
  if (!section) return text;
  const body = lines.slice(section.at + 1, section.end);
  const indent = /^(\s+)\S/.exec(body.find((line) => /^\s+\w/.test(line)) ?? "")?.[1] ?? "  ";
  const pattern =
    field === "provider"
      ? new RegExp(`^${indent}provider\\s*:`)
      : new RegExp(`^${indent}(?:"?default"?|model)\\s*:`);
  const at = body.findIndex((line) => pattern.test(line));
  if (recorded !== undefined) {
    if (at !== -1) {
      body[at] = recorded;
    } else if (field === "default") {
      // Beside the provider line, where pinHermesModel puts it.
      const providerKey = new RegExp(`^${indent}provider\\s*:`);
      const providerAt = body.findIndex((line) => providerKey.test(line));
      body.splice(providerAt !== -1 ? providerAt + 1 : body.length, 0, recorded);
    } else {
      // First, where pinHermesModel puts the provider line.
      body.unshift(recorded);
    }
    // The header is the bare `model:` key: a scalar sentinel left standing
    // in front of the restored mapping would not parse.
    return [...lines.slice(0, section.at), "model:", ...body, ...lines.slice(section.end)].join(
      "\n",
    );
  }
  if (at === -1) return text;
  body.splice(at, 1);
  if (body.every((line) => line.trim() === "")) {
    // Our lines were the section's whole body: drop the bare header too.
    return [...lines.slice(0, section.at), ...lines.slice(section.end)].join("\n");
  }
  return [...lines.slice(0, section.at), "model:", ...body, ...lines.slice(section.end)].join("\n");
}
